language: python
python:
  - "2.7"
before_install:
  - wget http://svn.zope.org/*checkout*/zc.buildout/trunk/bootstrap/bootstrap.py
  - python bootstrap.py
  - bin/buildout
script:
  - bin/py.test -v tests/bqlib_test.py
notifications:
  emails:
    - addsict@gmail.com
  on_success: always
  on_failure: always
