language: python
python:
  - "2.7"
before_install:
  - wget http://downloads.buildout.org/1/bootstrap.py
  - python bootstrap.py -v 1.7.0 -d
  - bin/buildout
script:
  - bin/py.test -v tests/bqlib_test.py
notifications:
  emails:
    - addsict@gmail.com
  on_success: always
  on_failure: always
